roles:
  - name: geerlingguy.mysql
  - name: geerlingguy.apache

collections:
  - name: netways.icinga
  - name: telekom_mms.icinga_director
  - name: community.general
  - name: ansible.windows
  - name: community.windows
  - name: icinga_contrib
    type: git
    source: https://github.com/donien/ansible-collection-icinga_contrib.git
    version: main